version: '3'
services:
  postgresql:
    container_name: postgresql
    image: bitnami/postgresql:latest
    expose:
      - "5432"
    tty: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    #    volumes:
    #      - ${POSTGRES_HOME_DIR}/data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  spring_boot:
    container_name: spring_boot
    image: ${SPRING_BOOT_IMAGE}
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      SPRING_DATASOURCE_URL: ${POSTGRES_URL}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    volumes:   프론트랑 합친 후에 볼륨 설정 예정