name: google-java-format # 워크플로우의 이름
on: [ pull_request ] # 깃 저장소의 push, pull_request 이벤트에 의해 트리거된다.
jobs:
  formatting:
    runs-on: ubuntu-latest # 워크플로우의 이름
    steps:
      - uses: actions/checkout@v2 # 깃허브 저장소를 체크아웃 하는 액션
      - uses: axel-op/googlejavaformat-action@v3 # 본격적인 google-java-format 실행
        with:
          args: "--replace" # --replace (파일을 수정한다)
          commit-message: "style: google-java-format"